version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=dharanikarthick66
      - MONGO_INITDB_ROOT_PASSWORD=Dharick@66
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build:
      context: ./server
    container_name: backend
    environment:
      - PORT=5000
      - MONGO_URI=mongodb+srv://dharanikarthick66:Dharick%4066@cluster0.bd3ipzx.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
    ports:
      - "5000:5000"
    depends_on:
      - mongo

  frontend:
    build:
      context: ./client
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  mongo-data:
